
tests-and-coverage:
  image: i10git.cs.fau.de:5005/pycodegen/pycodegen/full
  script:
    - export NUM_CORES=$(nproc --all)
    - mkdir -p ~/.config/matplotlib
    - mkdir public
    - python setup.py test
  tags:
    - docker
    - cuda
  artifacts:
    when: always
    paths:
      - test-report
